# -*- coding: utf-8 -*-
"""thresh_labels.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lrpb4kcAaWlklMgO2_YbMMTr69JbAxmz
"""

def thresh_label():
    print("Program started"+"\n")
    thresh_values=[3.5,4,5,6,6.5]
    for thresh_val in thresh_values:
      fout_labels_class = open("data/label_class_0_{}.dat".format(str(thresh_val)),'w')
      with open('data/32/labels_0.dat','r') as f:
          for val in f:
              if float(val) > float(thresh_val):
                  fout_labels_class.write(str(1) + "\n");
              else:
                  fout_labels_class.write(str(0) + "\n");    
      print("Encoded label 0"+"\n")


      fout_labels_class1 = open("data//label_class_1_{}.dat".format(str(thresh_val)),'w')
      with open('data/32/labels_1.dat','r') as f:
          for val in f:
              if float(val) > float(thresh_val):
                  fout_labels_class1.write(str(1) + "\n");
              else:
                  fout_labels_class1.write(str(0) + "\n");   
      print("Encoded label 1"+"\n")


      fout_labels_class2 = open("data/label_class_2_{}.dat".format(str(thresh_val)),'w')    
      with open('data/32/labels_2.dat','r') as f:
          for val in f:
              if float(val) > float(thresh_val):
                  fout_labels_class2.write(str(1) + "\n");
              else:
                  fout_labels_class2.write(str(0) + "\n");
      print("Encoded label 2"+"\n")


      fout_labels_class3 = open("data/label_class_3_{}.dat".format(str(thresh_val)),'w')
      with open('data/32/labels_3.dat','r') as f:
          for val in f:
              if float(val) > float(thresh_val):
                  fout_labels_class3.write(str(1) + "\n");
              else:
                  fout_labels_class3.write(str(0) + "\n");
      print("Encoded label 3"+"\n")
    
if __name__ == '__main__':
    thresh_label()

